---

- name: Is Peacock Room already installed?
  stat:
    path: /var/www/peacockroom
  register: peacockroom_installed
  changed_when: peacockroom_installed.stat.exists == False

- name: Clone Peacock Room Github repository
  git:
    repo: https://github.com/WSULib/peacockroom.git
    dest: /var/www/peacockroom
    version: "{{ peacockroom_git_branch }}"
  when: peacockroom_installed.stat.exists == False

- name: Set permissions
  file:
    path: /var/www/peacockroom
    recurse: yes
    owner: peacock
    group: www-data

- name: Copy the peacockroom.sql file to tmp
  template:
    src: peacockroom.sql
    dest: /tmp/peacockroom.sql
  when: peacockroom_installed.stat.exists == False

- name: Prepare Peacock Room Database
  mysql_db:
    config_file: /root/.my.cnf
    state: import
    name: all
    target: /tmp/peacockroom.sql
  when: peacockroom_installed.stat.exists == False

- name: Place Apache vhost file into the correct spot
  template:
    src: peacockroom.conf
    dest: /etc/apache2/sites-available/peacockroom.conf
  when: peacockroom_installed.stat.exists == False

- name: Enable Apache vhost file
  command: a2ensite peacockroom.conf
  when: peacockroom_installed.stat.exists == False

- name: Remove old/default vhost file
  command: rm /etc/apache2/sites-available/000-default.conf
  when: peacockroom_installed.stat.exists == False

- name: Configure database.ini
  template:
    src: database.ini
    dest: /var/www/peacockroom/config/database.ini
  when: peacockroom_installed.stat.exists == False

- name: Copy local.config.php
  template:
    src: local.config.php
    dest: /var/www/peacockroom/config/local.config.php
  when: peacockroom_installed.stat.exists == False

- name: Reset permissions
  file:
    path: /var/www/peacockroom
    recurse: yes
    owner: peacock
    group: www-data

- name: Make files directory writable
  file:
    path: /var/www/peacockroom/files
    owner: peacock
    group: www-data
    mode: 0664

- name: Restart Apache
  action: service name=apache2 state=restarted enabled=true